In [3]:
import pandas as pd

# Load sales data into a DataFrame
sales_data = pd.read_csv('D:\downloads\orders.csv')

# Group by product ID and sum the quantities sold
product_sales = sales_data.groupby('prod id')['quantity'].sum()

# Find the product with the highest total quantity sold
most_sold_product_id = product_sales.idxmax()
most_sold_quantity = product_sales.max()

# Get the product details for the most sold product
most_sold_product_details = sales_data.loc[sales_data['prod id'] == most_sold_product_id].iloc[0]

print("Most sold product ID:", most_sold_product_id)
print("Quantity sold:", most_sold_quantity)
print("Product details:")
print(most_sold_product_details)


Most sold product ID: 7
Quantity sold: 7
Product details:
order_id           7
cust id            2
prod id            7
date        4.4.2024
quantity           7
Name: 6, dtype: object


In [5]:
import pandas as pd

# Load the orders data
orders_df = pd.read_csv('D:\downloads\orders.csv')

# Group by product ID and sum the quantities sold
product_sales = orders_df.groupby('prod id')['quantity'].sum()

# Find the product with the highest total quantity sold
most_sold_product_id = product_sales.idxmax()
most_sold_quantity = product_sales.max()

print("Most sold product ID:", most_sold_product_id)
print("Quantity sold:", most_sold_quantity)


Most sold product ID: 7
Quantity sold: 7


In [11]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import BernoulliNB
from sklearn.metrics import confusion_matrix, accuracy_score

# Load the orders data
orders_df = pd.read_csv('D:\downloads\orders.csv')

# Define a binary target variable based on certain conditions (e.g., high-value order)
threshold = 100  # Example threshold for high-value order
orders_df['is_high_value'] = (orders_df['prod id'] > threshold).astype(int)

# Select features and target variable
X = orders_df[['quantity']]  # Example feature
y = orders_df['is_high_value']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train a Bernoulli Naive Bayes classifier
model = BernoulliNB()
model.fit(X_train, y_train)

# Predict the labels on the test set
y_pred = model.predict(X_test)

# Compute the confusion matrix
cm = confusion_matrix(y_test, y_pred)

# Print the confusion matrix
print("Confusion Matrix:")
print(cm)

# Compute the accuracy of the model
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)


Confusion Matrix:
[[2]]
Accuracy: 1.0


In [12]:
import numpy as np

In [13]:
s = 5


In [15]:
s

5

In [16]:
v = np.array([5,-2,4])

In [18]:
v

array([ 5, -2,  4])

In [19]:
m = np.array([[5,12,6],[4,-6,4]])

In [21]:
m

array([[ 5, 12,  6],
       [ 4, -6,  4]])

In [22]:
type(s)


int

In [23]:
type(v)

numpy.ndarray

In [24]:
type(m)

numpy.ndarray

In [26]:
s_array = np.array(s)
s_array

array(5)

In [27]:
type(s_array)


numpy.ndarray

In [29]:
m.shape


(2, 3)

In [31]:
v.reshape(1,3)

array([[ 5, -2,  4]])

In [38]:
t_manual = np.array([[1,2,3],[15,6,7]])
t_manual

array([[ 1,  2,  3],
       [15,  6,  7]])

In [35]:
m1 = np.array([[5,1,5],[3,-9,8]])
m1

array([[ 5,  1,  5],
       [ 3, -9,  8]])

In [39]:
m2 = np.array([[75,941,50],[8,-90,86]])
m2

array([[ 75, 941,  50],
       [  8, -90,  86]])

In [41]:
t = np.array([m1,m2])
t

array([[[  5,   1,   5],
        [  3,  -9,   8]],

       [[ 75, 941,  50],
        [  8, -90,  86]]])

In [43]:
t.shape

(2, 2, 3)

In [45]:
m1+ m2

array([[ 80, 942,  55],
       [ 11, -99,  94]])

In [47]:
m2 - m1

array([[ 70, 940,  45],
       [  5, -81,  78]])

In [49]:
v1 = np.array([1,2,3,4,5])
v2 = np.array([8,2,3,4,9])

In [51]:
v1 + v2

array([ 9,  4,  6,  8, 14])

In [53]:
v1 - v2

array([-7,  0,  0,  0, -4])

In [54]:
m1 + 1

array([[ 6,  2,  6],
       [ 4, -8,  9]])

In [56]:
v1 + 1

array([2, 3, 4, 5, 6])

In [59]:
v1 + np.array([1])

array([2, 3, 4, 5, 6])

In [62]:
m1.T

array([[ 5,  3],
       [ 1, -9],
       [ 5,  8]])

In [64]:
5*m1

array([[ 25,   5,  25],
       [ 15, -45,  40]])

In [66]:
np.dot(v1,v2)

82

In [71]:
m3 = np.array([[[5,1],[3,-9],[8,6]]])
m3

array([[[ 5,  1],
        [ 3, -9],
        [ 8,  6]]])

In [74]:
np.dot(m1,m3)

array([[[ 68,  26]],

       [[ 52, 132]]])