In [1]:
import numpy as np
import pandas as pd
import statsmodels.api as sm
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

from scipy import stats
stats.chisqprob = lambda chisq, df: stats.chi2.sf(chisq, df)

In [4]:
raw_data = pd.read_csv('D:\downloads\sons.csv')
raw_data                

STUDENT   SAT   GPA  RAND 1,2,3 ADMITTANCE GENDER
0       A  1900  5.00           1        YES      M
1       B  1890  4.01           3         NO      F
2       C  1750  3.65           3        YES      M
3       D  1800  4.55           3        YES      F
4       E  1987  5.10           2         NO      M

In [6]:
data = raw_data.copy()
data['ADMITTANCE'] = data['ADMITTANCE'].map({'YES':1,'NO':0})
data['GENDER'] = data['GENDER'].map({'F':1,'M':0})
data
                                        

STUDENT   SAT   GPA  RAND 1,2,3  ADMITTANCE  GENDER
0       A  1900  5.00           1           1       0
1       B  1890  4.01           3           0       1
2       C  1750  3.65           3           1       0
3       D  1800  4.55           3           1       1
4       E  1987  5.10           2           0       0

In [18]:
y = data['ADMITTANCE']
x1 = data[['SAT','GENDER']]

In [20]:
x = sm.add_constant(x1)
reg_log = sm.Logit(y,x)
results_log = reg_log.fit()
results_log.summary()

         Current function value: inf
         Iterations: 35


D:\anaconda\Lib\site-packages\statsmodels\discrete\discrete_model.py:2383: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
D:\anaconda\Lib\site-packages\statsmodels\discrete\discrete_model.py:2441: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q * linpred)))


LinAlgError: Singular matrix

In [21]:
np.exp(1.949)

7.021662406181339

In [28]:
np.set_printoptions(formatter={'float': lambda x: "{0:0.2f}".format(x)})
results_log.predict()

array([0.67, 0.50, 0.67, 0.50, 0.67])

In [30]:
np.array(data['ADMITTANCE'])

array([1, 0, 1, 1, 0], dtype=int64)

In [32]:
results_log.pred_table()

array([[1.00, 1.00],
       [1.00, 2.00]])

In [35]:
cm_df = pd.DataFrame(results_log.pred_table())
cm_df.columns = ['Predicted 0','Predicted 1']
cm_df = cm_df.rename(index={0:'Actual 0',1:'Actual 1'})
cm_df

Predicted 0  Predicted 1
Actual 0          1.0          1.0
Actual 1          1.0          2.0

In [45]:
test = pd.read_csv('D:\downloads\sons.csv')
test

STUDENT   SAT   GPA  RAND 1,2,3 ADMITTANCE GENDER
0       A  1900  5.00           1        YES      M
1       B  1890  4.01           3         NO      F
2       C  1750  3.65           3        YES      M
3       D  1800  4.55           3        YES      F
4       E  1987  5.10           2         NO      M

In [46]:
test['ADMITTANCE'] = test['ADMITTANCE'].map({'YES' : 1, 'NO': 0})
test['GENDER']= test['GENDER'].map({'F': 1,'M': 0})
test

STUDENT   SAT   GPA  RAND 1,2,3  ADMITTANCE  GENDER
0       A  1900  5.00           1           1       0
1       B  1890  4.01           3           0       1
2       C  1750  3.65           3           1       0
3       D  1800  4.55           3           1       1
4       E  1987  5.10           2           0       0

In [48]:
x

const   SAT  GENDER
0    1.0  1900       0
1    1.0  1890       1
2    1.0  1750       0
3    1.0  1800       1
4    1.0  1987       0

In [50]:
test_actual = test['ADMITTANCE']
test_data = test.drop(['ADMITTANCE'],axis=1)
test_data = sm.add_constant(test_data)
test_data


const STUDENT   SAT   GPA  RAND 1,2,3  GENDER
0    1.0       A  1900  5.00           1       0
1    1.0       B  1890  4.01           3       1
2    1.0       C  1750  3.65           3       0
3    1.0       D  1800  4.55           3       1
4    1.0       E  1987  5.10           2       0

In [61]:
def confusion_matrix(data,actual_values,model):
    
      pred_values = model.predict(data)
      bins=np.array([0,0.5,1])
      cm = np.histogram2d(actual_values, pred_values, bins-bins)[0]
      accuracy = (cm[0,0]+cm[1,1])/cm.sum()
      return cm, accuracy

In [63]:
cm = confusion_matrix(test_data,test_actual,results_log)
cm

ValueError: shapes (5,6) and (2,) not aligned: 6 (dim 1) != 2 (dim 0)

In [64]:
print ('Missclassification rate:'+str((1+1)/19))

Missclassification rate:0.10526315789473684
