In [1]:
import numpy as np
from sklearn.model_selection import train_test_split


In [3]:
a = np.arange(1,101)


In [5]:
a

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [7]:
b = np.arange(501,601)
b

array([501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513,
       514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526,
       527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539,
       540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550, 551, 552,
       553, 554, 555, 556, 557, 558, 559, 560, 561, 562, 563, 564, 565,
       566, 567, 568, 569, 570, 571, 572, 573, 574, 575, 576, 577, 578,
       579, 580, 581, 582, 583, 584, 585, 586, 587, 588, 589, 590, 591,
       592, 593, 594, 595, 596, 597, 598, 599, 600])

In [9]:
train_test_split(a)

[array([  7,  85,  46,  74,  68,  56,  69,  50,   2,   1,  49,  12,  41,
         47,  95,  98,  91,  16,  38,  10,  52,  58,  15,  33,  82,  27,
         67,  29,  89,  99,  35,  73,  13,  53,  76,  24,  92,   4,  40,
         81,  79,  42,  70,  94,   5,  44,  72, 100,  51,   3,  62,  64,
         37,  11,  55,  22,  86,  93,  23,  60,  19,  75,  25,  61,  83,
         66,  31,  48,  71,  87,  63,  34,  21,  32,  45]),
 array([36, 18, 26, 43,  9,  6, 17, 39, 65, 96, 97,  8, 59, 30, 78, 77, 54,
        88, 28, 80, 90, 20, 57, 84, 14])]

In [18]:
a_train,a_test,b_train,b_test = train_test_split(a, b, test_size=0.2, random_state=365)

In [11]:
a_train.shape, a_test.shape

((75,), (25,))

In [13]:
a_train

array([ 77,  12,  84,   3,  60,   8,  69,  52,  81,  15,  65,  17,  68,
        29,  96,  91,  14,  35,  85,  53,  46,  32,  61,  62,  55,   6,
        64,  44,  78,  33,  70,  47,  26,  39,  71,  92, 100,  98,  83,
        59,  13,  97,  72,  80,   2,  30,  54,  89,  95,  73,  58,  40,
         4,  93,  99,  49,  11,  86,   7,  82,  41,  19,  36,  34,  88,
        38,  28,  66,  45,  79,  76,  42,  75,  18,  20])

In [16]:
a_test

array([70, 42, 67, 72,  5, 16, 87, 29, 40, 62, 95, 58, 53, 90, 37, 44, 66,
       61, 48, 80])

In [19]:
b_train.shape, b_test.shape

((80,), (20,))

In [21]:
b_train

array([525, 532, 599, 573, 591, 566, 503, 559, 594, 501, 508, 515, 590,
       554, 531, 520, 577, 582, 530, 535, 595, 542, 538, 507, 511, 550,
       521, 548, 502, 517, 510, 558, 568, 543, 541, 516, 588, 572, 579,
       600, 580, 539, 524, 586, 522, 523, 562, 576, 518, 547, 555, 526,
       560, 519, 571, 564, 551, 563, 565, 528, 512, 578, 513, 544, 575,
       587, 540, 504, 529, 549, 537, 557, 527, 574, 506, 545, 592, 534,
       553, 583])

In [22]:
b_test

array([509, 569, 581, 556, 533, 593, 584, 561, 546, 589, 585, 567, 597,
       505, 570, 536, 598, 596, 514, 552])